# -*- coding: utf-8 -*-
"""python project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BOsPbDKOKDkAYwfCqzcm8jyPXeBpV7u
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv



df = pd.read_csv('/content/drive/MyDrive/project python/fact_trips.csv')
df1 = pd.read_csv('/content/drive/MyDrive/project python/city_target_passenger_rating.csv')
df2 = pd.read_csv('/content/drive/MyDrive/project python/dim_city.csv')
df3 = pd.read_csv('/content/drive/MyDrive/project python/dim_date.csv')
df4 = pd.read_csv('/content/drive/MyDrive/project python/dim_repeat_trip_distribution.csv')
df5 = pd.read_csv('/content/drive/MyDrive/project python/fact_passenger_summary.csv')
df6 = pd.read_csv('/content/drive/MyDrive/project python/monthly_target_new_passengers.csv')
df7 = pd.read_csv('/content/drive/MyDrive/project python/monthly_target_trips.csv')

df.head()

df1.head()

df2.head()

df3.head()

df4.head()

df5.head()

df6.head()

df7.head()

df.info()
df.shape

"""1.	Top and Bottom Performing Cities
•	Identify the top 3 and bottom 3 cities by total trips over the entire analysis period.

"""

finaldf=pd.merge(df,df2,how='left',on='city_id')
finaldf
#Here I am trying to find the top 3 an bottom trips by city for that i merged the dimension data table with the fact table

finaldf1=pd.merge(finaldf,df1,how='left',on='city_id')
finaldf1

finaldf.isnull().sum()

"""TOP AND Bottom CITIES


"""

city_count=finaldf.groupby('city_name').agg(City=('city_name', 'count'))
print(city_count.sort_values(by='City',ascending=False).head(3))
print(city_count.sort_values(by='City',ascending=False).tail(3))
#here i am am found that the city names with

sorted_city_count = city_count.sort_values(by='City', ascending=False)
display(sorted_city_count)

print('Top 3 Cities:')
display(sorted_city_count.head(3))

print('\nBottom 3 Cities:')
display(sorted_city_count.tail(3))

"""2.	Average Fare per Trip by City
  Calculate the average fare per trip for each city and compare it with the city's average trip distance. Identify the cities with the highest and lowest average fare per trip to assess pricing efficiency across locations.

Average fare per city and Average Trip Distance
"""

city_avg_fare=finaldf.groupby('city_name').agg(average_fare=('fare_amount','mean'),
                                            average_distance=('distance_travelled(km)','mean'))
city_avg_fare
# here i found the city avg fare by using groupby function and aggergate function

"""3.	Average Ratings by City and Passenger Type
•	Calculate the average passenger and driver ratings for each city, segmented by passenger type (new vs. repeat). Identify cities with the highest and lowest average ratings.

Average Rating by Passanger Type by Driver and Passanger
"""

city_avg_Rating=finaldf.groupby(['city_name','passenger_type']).agg(average_P_Rating=('passenger_rating','mean'),
                                            average_D_Rating=('driver_rating','mean'))
city_avg_Rating
# here i found the avg rating by passanger and the driver by per trip using groupby and aggregate function



"""here i am trying To identify cities with the highest and lowest average passenger and driver ratings across all passenger types, I will first calculate the overall average passenger and driver ratings for each city by grouping `city_passenger_type_avg_ratings` by `city_name` and taking the mean. Then, I will find the city with the maximum and minimum values for each rating type.
To calculate the average 'passenger_rating' and 'driver_rating' for each 'city_name' and 'passenger_type', I will group the 'finaldf' DataFrame by these two columns and apply the mean aggregation. **bold text**

"""

highest_avg_passenger_rating_city= city_avg_Rating['average_P_Rating'].idxmax()
lowest_avg_passenger_rating_city = city_avg_Rating['average_P_Rating'].idxmin()
highest_avg_driver_rating_city = city_avg_Rating['average_D_Rating'].idxmax()
lowest_avg_driver_rating_city = city_avg_Rating['average_D_Rating'].idxmin()
print(f"{highest_avg_passenger_rating_city} ({city_avg_Rating['average_P_Rating'].max():.2f})")
print(f"{lowest_avg_passenger_rating_city} ({city_avg_Rating['average_P_Rating'].min():.2f})")
print(f"{highest_avg_driver_rating_city} ({city_avg_Rating['average_D_Rating'].max():.2f})")
print(f"{lowest_avg_driver_rating_city} ({city_avg_Rating['average_D_Rating'].min():.2f})")
#To calculate the average 'passenger_rating' and 'driver_rating' for each 'city_name' and 'passenger_type', I will group the 'finaldf'
#DataFrame by these two columns and apply the mean aggregation.

import matplotlib.pyplot as plt
#Reasoning: To visualize the average passenger and driver ratings for each city and passenger type, I will create bar charts. First,
#I need to reset the index of the city_passenger_type_avg_ratings DataFrame to convert the multi-index into columns, which makes it easier to plot.
# Reset index to make 'city_name' and 'passenger_type' regular columns for plotting
plot_df = city_avg_Rating.reset_index()

# Create separate plots for average passenger rating and average driver rating
fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(15, 12), sharex=True)

# Plot Average Passenger Rating
plot_df.pivot(index='city_name', columns='passenger_type', values='average_P_Rating').plot(kind='bar', ax=axes[0])
axes[0].set_title('Average Passenger Rating by City and Passenger Type')
axes[0].set_ylabel('Average Passenger Rating')
axes[0].set_xlabel('')
axes[0].tick_params(axis='x', rotation=45)
axes[0].legend(title='Passenger Type')

# Plot Average Driver Rating
plot_df.pivot(index='city_name', columns='passenger_type', values='average_D_Rating').plot(kind='bar', ax=axes[1])
axes[1].set_title('Average Driver Rating by City and Passenger Type')
axes[1].set_ylabel('Average Driver Rating')
axes[1].set_xlabel('City Name')
axes[1].tick_params(axis='x', rotation=45)
axes[1].legend(title='Passenger Type')

plt.tight_layout()
plt.show()



"""4.	Peak and Low Demand Months by City
•	For each city, identify the month with the highest total trips (peak demand) and the month with the lowest total trips (low demand). This analysis will help Goodcabs understand seasonal patterns and adjust resources accordingly.

"""

#Reasoning: Before merging, I will convert the 'date' column in both finaldf and df3
#to datetime objects to ensure proper merging and handling of date information.
finaldf['date'] = pd.to_datetime(finaldf['date'])

df3['date'] = pd.to_datetime(df3['date'])

merged_df = pd.merge(finaldf, df3, on='date', how='left')
merged_df.head()

"""**Reasoning**:
Now that the dataframes are merged and contain month information, I will calculate the total number of trips per city per month by grouping the `merged_df` by `city_name` and `month_name` and then counting the occurrences of `trip_id`.


"""

#Reasoning: Now that the dataframes are merged and contain month information, I will calculate the total number of trips per city per month
#by grouping the merged_df by city_name and month_name and then counting the occurrences of trip_id
monthly_trips = merged_df.groupby(['city_name', 'month_name']).agg(total_trips=('trip_id', 'count'))# can add here.resetindex()
monthly_trips.head()

month_order = ['January', 'February', 'March', 'April', 'May', 'June']

# Recalculated monthly_trips from merged_df to ensure a clean state
monthly_trips = merged_df.groupby(['city_name', 'month_name']).agg(total_trips=('trip_id', 'count')).reset_index()

# Converted 'month_name' to a categorical type with specified order
monthly_trips['month_name'] = pd.Categorical(monthly_trips['month_name'], categories=month_order, ordered=True)

# Sorted the DataFrame by 'total_trips' in descending order
monthly_trips = monthly_trips.sort_values(by='total_trips', ascending=False)

monthly_trips.head()

#To identify peak and low demand months for each city, I grouped the monthly_trips DataFrame by city_name
#and then use aggregation functions to find the month corresponding to the maximum and minimum total_trips for each city.

peak_low_demand = monthly_trips.groupby('city_name').agg(
    peak_month=('month_name', lambda x: x.loc[x.idxmax()]),
    peak_trips=('total_trips', 'max'),
    low_month=('month_name', lambda x: x.loc[x.idxmin()]),
    low_trips=('total_trips', 'min')
)
print(peak_low_demand)

import matplotlib.pyplot as plt
import seaborn as sns

# Created a figure for the plot with a suitable size
plt.figure(figsize=(15, 8))

# Generated a line plot showing total trips per month for each city
sns.lineplot(data=monthly_trips, x='month_name', y='total_trips', hue='city_name', marker='o')

# Setting the title of the plot
plt.title('Monthly Total Trips by City')

# Labelelling the x-axis and y-axis
plt.xlabel('Month')
plt.ylabel('Total Trips')

# Rotate the x-axis labels by 45 degrees to prevent overlap
plt.xticks(rotation=45)

# Adding a legend to the plot with the title 'City Name', placed outside the plot area
plt.legend(title='City Name', bbox_to_anchor=(1.05, 1), loc='upper left')

# Adding a grid to the plot for easier interpretation
plt.grid(True)

# Adjusting the plot layout to prevent labels from overlapping
plt.tight_layout()

# Display the plot
plt.show()

trip_demand=merged_df.groupby(['city_name','day_type']).agg(trip_count=('day_type','count'))

trip_demand
#calculated the trip demand by doing simple groupby with merged df and calculated the trip count

df4

df2

#To aggregate df4 and then merge it with df2, I did first groupby df4by city_id and trip_count
#and sum repeat_passenger_count. Then I did  merge the result with df2 on city_id to add city_name.
#used left merge because repeat trip frequency has a big data than the df2

repeat_trip_frequency = df4.groupby(['city_id', 'trip_count']).agg(total_repeat_passengers=('repeat_passenger_count', 'sum')).reset_index()
repeat_trip_frequency = pd.merge(repeat_trip_frequency, df2, on='city_id', how='left')
repeat_trip_frequency

#To calculate the percentage of repeat passengers within each trip_count category for each city,
#I am first calculated the total number of repeat passengers per city.
#Then, I merged this total back into the repeat_trip_frequency DataFrame and compute the percentage for each category.
city_total_repeat_passengers = repeat_trip_frequency.groupby('city_name')['total_repeat_passengers'].sum().reset_index()
city_total_repeat_passengers

"""**Question 6**.	Repeat Passenger Frequency and City Contribution Analysis
•	Analyse the frequency of trips taken by repeat passengers in each city (e.g., % of repeat passengers taking 2 trips, 3 trips, etc.). Identify which cities contribute most to higher trip frequencies among repeat passengers, and examine if there are distingu ishable patterns between tourism-focused and business-focused cities.

"""

city_total_repeat_passengers.rename(columns={'total_repeat_passengers': 'overall_city_total_repeat_passengers'}, inplace=True)

repeat_trip_frequency = pd.merge(repeat_trip_frequency, city_total_repeat_passengers, on='city_name', how='left')

repeat_trip_frequency['percentage_of_total_repeat_passengers'] = (repeat_trip_frequency['total_repeat_passengers'] / repeat_trip_frequency['overall_city_total_repeat_passengers']) * 100

repeat_trip_frequency.head()

#To identify cities with a higher proportion of repeat passengers taking more trips, Idid first filter the repeat_trip_frequency DataFrame
#to include only the '5-Trips' and '10-Trips' categories.Then, I will group by city_name and sum the percentage_of_total_repeat_passengers for these categories.

high_frequency_trips = repeat_trip_frequency[repeat_trip_frequency['trip_count'].isin(['5-Trips', '10-Trips'])]

city_high_frequency_percentage = high_frequency_trips.groupby('city_name')['percentage_of_total_repeat_passengers'].sum().sort_values(ascending=False).reset_index()

print("Cities with higher proportion of repeat passengers taking more trips (5-Trips and 10-Trips):")
print(city_high_frequency_percentage)

"""**Reasoning**:
To categorize cities into 'Tourism' and 'Business' based on general knowledge, I will define a dictionary mapping each city to its respective category. This dictionary will then be used to create a new 'city_category' column in the `repeat_trip_frequency` DataFrame. This setup is crucial for analyzing repeat trip frequency patterns between the two city types.


"""

city_category_mapping = {
    'Jaipur': 'Tourism',
    'Kochi': 'Tourism',
    'Visakhapatnam': 'Tourism', # Assuming Visakhapatnam has significant tourism due to coastal location
    'Mysore': 'Tourism', # Famous for palaces and heritage
    'Chandigarh': 'Business', # Known for its planned architecture and IT industry
    'Coimbatore': 'Business', # Industrial hub
    'Indore': 'Business', # Commercial capital of Madhya Pradesh
    'Lucknow': 'Business', # Administrative and educational hub
    'Surat': 'Business', # Diamond and textile hub
    'Vadodara': 'Business' # Industrial and educational hub
}

repeat_trip_frequency['city_category'] = repeat_trip_frequency['city_name'].map(city_category_mapping)
repeat_trip_frequency.head()

"""**Reasoning**:
Now that the cities are categorized, I will group the `repeat_trip_frequency` DataFrame by `city_category` and `trip_count` and calculate the mean of `percentage_of_total_repeat_passengers` to analyze patterns between 'Tourism' and 'Business' cities.


"""

category_frequency_patterns = repeat_trip_frequency.groupby(['city_category', 'trip_count']).agg(
    mean_percentage_repeat_passengers=('percentage_of_total_repeat_passengers', 'mean')
).reset_index()

# Sort by trip_count for better readability (e.g., 2-Trips, 3-Trips, ..., 10-Trips)
# First, convert 'trip_count' to a categorical type with a specific order
trip_count_order = ['2-Trips', '3-Trips', '4-Trips', '5-Trips', '10-Trips']
category_frequency_patterns['trip_count'] = pd.Categorical(
    category_frequency_patterns['trip_count'],
    categories=trip_count_order,
    ordered=True
)
category_frequency_patterns = category_frequency_patterns.sort_values(by=['city_category', 'trip_count'])

print("Average percentage of repeat passengers by city category and trip count:")
print(category_frequency_patterns)

"""**Reasoning**:
To visualize the average percentage of repeat passengers by city category and trip count, I will create a grouped bar chart using the `category_frequency_patterns` DataFrame. This will clearly show the patterns between 'Tourism' and 'Business' cities for different trip frequencies.


"""

# Create a figure for the plot with a suitable size
plt.figure(figsize=(12, 7))

# Generate a grouped bar chart
sns.barplot(data=category_frequency_patterns, x='trip_count', y='mean_percentage_repeat_passengers', hue='city_category', palette='viridis')

# Set the title of the plot
plt.title('Average Percentage of Repeat Passengers by City Category and Trip Count')

# Label the x-axis and y-axis
plt.xlabel('Trip Count Category')
plt.ylabel('Mean Percentage of Repeat Passengers')

# Add a legend to the plot
plt.legend(title='City Category')

# Ensure tight layout and display the plot
plt.tight_layout()
plt.show()

"""7.	Month ly Target Ach ievement Analysis for Key Metrics
  For each city, evaluate monthly performance against targets for total trips, new passengers, and average passenger ratings from targets db. Determine if each metric met, exceeded, or missed the target, and calculate the percentage difference. Identify any consistent patterns in target ach ievement, particularly across tou rism versus business-focused cities.

"""

df7['month'] = pd.to_datetime(df7['month'])
print("df7 'month' column converted to datetime.")
df7.head()

"""**Reasoning**:
I will group the `merged_df` by 'city_id', 'city_name', and 'start_of_month' to count the total `trip_id` for each city per month, creating `actual_monthly_trips` as instructed.


"""

actual_monthly_trips = merged_df.groupby(['city_id', 'city_name', 'start_of_month']).agg(actual_total_trips=('trip_id', 'count')).reset_index()
actual_monthly_trips.head()

"""**Reasoning**:
I need to rename the 'start_of_month' column in `actual_monthly_trips` to 'month' to align with the column name in `df7` for the upcoming merge.


"""

actual_monthly_trips = actual_monthly_trips.rename(columns={'start_of_month': 'month'})
actual_monthly_trips.head()

"""**Reasoning**:
Now that `actual_monthly_trips` and `df7` both have a 'month' column in datetime format, I will merge them using 'city_id' and 'month' as keys to combine actual and target trip data. I will use a left merge to retain all actual trips.


"""

actual_monthly_trips.head()

df7.head()

actual_monthly_trips['month'] = pd.to_datetime(actual_monthly_trips['month'])
df7['month'] = pd.to_datetime(df7['month'])

total_trips_achievement = pd.merge(actual_monthly_trips, df7, on=['city_id','month'], how='left')
total_trips_achievement.head()

"""**Reasoning**:
The error indicates a type mismatch between the 'month' columns during the merge operation. Although previous steps intended to convert them to datetime, I will explicitly convert both 'month' columns in `actual_monthly_trips` and `df7` to `datetime64[ns]` again immediately before merging to ensure type consistency and prevent the `ValueError`. Then, I will proceed with the merge and the subsequent calculations for achievement status and percentage difference.


"""

# Explicitly ensure 'month' columns are datetime before merging
# Calculate total_trip_percentage_difference
total_trips_achievement['total_trip_percentage_difference'] = (
    (total_trips_achievement['actual_total_trips'] - total_trips_achievement['total_target_trips']) /
    total_trips_achievement['total_target_trips']
) * 100

# Determine total_trip_achievement_status
conditions = [
    total_trips_achievement['actual_total_trips'] >= total_trips_achievement['total_target_trips']
]
choices = ['Target Achieved']
total_trips_achievement['total_trip_achievement_status'] = np.select(conditions, choices, default='Target Not Achieved')

total_trips_achievement.head()

df6.head()

"""**Reasoning**:
To ensure consistency for merging, I will first convert the 'month' column in both `df5` and `df6` DataFrames to datetime objects as specified in the first instruction.


"""

df5['month'] = pd.to_datetime(df5['month'])
df6['month'] = pd.to_datetime(df6['month'])
df5.head()
print("df5 and df6 'month' columns converted to datetime.")

df5.head()

"""**Reasoning**:
Now that the 'month' columns are in datetime format, I will merge `df5` and `df6` on 'city_id' and 'month', then merge the result with `df2` on 'city_id' to include the city names. Following this, I will calculate the percentage difference and achievement status for new passengers as per the instructions.


"""

new_passengers_achievement = pd.merge(df5, df6, on=['city_id', 'month'], how='left')
new_passengers_achievement = pd.merge(new_passengers_achievement, df2, on='city_id', how='left')

# Calculate new_passenger_percentage_difference
new_passengers_achievement['new_passenger_percentage_difference'] = (
    (new_passengers_achievement['new_passengers'] - new_passengers_achievement['target_new_passengers']) /
    new_passengers_achievement['target_new_passengers']
) * 100

# Determine new_passenger_achievement_status we used np.select like where or if else function
conditions = [
    new_passengers_achievement['new_passengers'] >= new_passengers_achievement['target_new_passengers']
]
choices = ['Target Achieved']
new_passengers_achievement['new_passenger_achievement_status'] = np.select(conditions, choices, default='Target Not Achieved')

new_passengers_achievement.head()

"""**Reasoning**:
To calculate the actual monthly average passenger ratings, I will group the `merged_df` by `city_id`, `city_name`, and `start_of_month`, and then compute the mean of the `passenger_rating`.


"""

actual_monthly_avg_ratings = merged_df.groupby(['city_id', 'city_name', 'start_of_month']).agg(actual_avg_passenger_rating=('passenger_rating', 'mean')).reset_index()
actual_monthly_avg_ratings.head()

"""**Reasoning**:
To continue with the analysis, I will rename the 'start_of_month' column to 'month' in `actual_monthly_avg_ratings` for consistency, then merge this DataFrame with `df1` on 'city_id' to incorporate target ratings. Finally, I will calculate the percentage difference and achievement status for average passenger ratings as instructed.


"""

import numpy as np

# Rename 'start_of_month' to 'month'
actual_monthly_avg_ratings = actual_monthly_avg_ratings.rename(columns={'start_of_month': 'month'})

# Merge with df1 for target_avg_passenger_rating
avg_passenger_rating_achievement = pd.merge(actual_monthly_avg_ratings, df1, on='city_id', how='left')

# Calculate avg_passenger_rating_percentage_difference
avg_passenger_rating_achievement['avg_passenger_rating_percentage_difference'] = (
    (avg_passenger_rating_achievement['actual_avg_passenger_rating'] - avg_passenger_rating_achievement['target_avg_passenger_rating']) /
    avg_passenger_rating_achievement['target_avg_passenger_rating']
) * 100

# Determine avg_passenger_rating_achievement_status
conditions = [
    avg_passenger_rating_achievement['actual_avg_passenger_rating'] >= avg_passenger_rating_achievement['target_avg_passenger_rating']
]
choices = ['Target Achieved ']
avg_passenger_rating_achievement['avg_passenger_rating_achievement_status'] = np.select(conditions, choices, default='Target Not Achieved')

avg_passenger_rating_achievement.head()

"""**Reasoning**:
To combine the achievement data, I will first merge `total_trips_achievement` with `new_passengers_achievement` on `city_id` and `month`. Then, I will merge the resulting DataFrame with `avg_passenger_rating_achievement` on the same keys to create the final `master_achievement_df`.


"""

total_trips_achievement['month'] = pd.to_datetime(total_trips_achievement['month']) #i made sure that the before merge dated format in same.
new_passengers_achievement['month'] = pd.to_datetime(new_passengers_achievement['month'])
avg_passenger_rating_achievement['month'] = pd.to_datetime(avg_passenger_rating_achievement['month'])

master_achievement_df = pd.merge(total_trips_achievement, new_passengers_achievement, on=['city_id', 'month'], how='left')
master_achievement_df = pd.merge(master_achievement_df, avg_passenger_rating_achievement, on=['city_id', 'month'], how='left')
master_achievement_df.head()

#To categorize cities in master_achievement_df into 'Tourism' and 'Business' and then analyze achievement patterns,
#I applied the existing city_category_mapping to the city_name_x column of master_achievement_df to create a new city_category
#column.Then I did group by this new category and calculate the mean of the specified percentage differences.
city_category_mapping = {
    'Jaipur': 'Tourism',
    'Kochi': 'Tourism',
    'Visakhapatnam': 'Tourism', # Assuming Visakhapatnam has significant tourism due to coastal location
    'Mysore': 'Tourism', # Famous for palaces and heritage
    'Chandigarh': 'Business', # Known for its planned architecture and IT industry
    'Coimbatore': 'Business', # Industrial hub
    'Indore': 'Business', # Commercial capital of Madhya Pradesh
    'Lucknow': 'Business', # Administrative and educational hub
    'Surat': 'Business', # Diamond and textile hub
    'Vadodara': 'Business' # Industrial and educational hub
}

master_achievement_df['city_category'] = master_achievement_df['city_name_x'].map(city_category_mapping)

# Group by 'city_category' and calculate the mean of the percentage differences
categorized_achievement_summary = master_achievement_df.groupby('city_category').agg(
    mean_total_trip_diff=('total_trip_percentage_difference', 'mean'),
    mean_new_passenger_diff=('new_passenger_percentage_difference', 'mean'),
    mean_avg_passenger_rating_diff=('avg_passenger_rating_percentage_difference', 'mean')
)

print("Average achievement patterns by city category:")
print(categorized_achievement_summary)

"""8.	Highest and Lowest Repeat Passenger Rate (RPR%) by City and Month
 	Analyse the Repeat Passenger Rate (RPR%) for each city across the sixmonth period. Identify the top 2 and bottom 2 cities based on their RPR% to determine which locations have the strongest and weakest rates.
 	Similarly, analyse the RPR% by month across all cities and identify the months with the highest and lowest repeat passenger rates. This will help to pinpoint any seasonal patterns or months with higher repeat passenger loyalty.

"""

#To calculate the RPR% for each city per month, I created a new column 'RPR%' in df5 by dividing 'repeat_passengers' by 'total_passengers'
#and multiplying by 100. This directly addresses the first instruction of the subtask.
df5['RPR%'] = (df5['repeat_passengers'] / df5['total_passengers']) * 100
df5.head()

#Now that the 'RPR%' has been calculated and added to df5, I merged df5 with df2 on the 'city_id' column to include the city_name in the DataFrame,
#storing the result in rpr_df and displaying its head to verify the merge, as instructed.
rpr_df = pd.merge(df5, df2, on='city_id', how='left')
rpr_df.head()

#calculate the average RPR% for each city across the six-month period, I didgroupby the rpr_df DataFrame by
#'city_name' and compute the mean of the 'RPR%' column.

city_avg_rpr = rpr_df.groupby('city_name')['RPR%'].mean().reset_index()
city_avg_rpr.head()

"""**Reasoning**:
To identify and display the top 2 cities with the highest average RPR% and the bottom 2 cities with the lowest average RPR%, I will sort the `city_avg_rpr` DataFrame in descending order for top cities and ascending order for bottom cities, then display the head and tail respectively.


"""

print('Top 2 Cities with Highest Average RPR%:')
display(city_avg_rpr.sort_values(by='RPR%', ascending=False).head(2))

print('\nBottom 2 Cities with Lowest Average RPR%:')
display(city_avg_rpr.sort_values(by='RPR%', ascending=True).head(2))

#To calculate the average RPR% for each month across all cities, I did groupbythe rpr_df DataFrame by the 'month'
#column and compute the mean of the 'RPR%' column.
monthly_avg_rpr = rpr_df.groupby('month')['RPR%'].mean().reset_index()
monthly_avg_rpr.head()

"""**Reasoning**:
To identify and display the month with the highest and lowest average RPR%, I will find the `idxmax()` and `idxmin()` of the 'RPR%' column in `monthly_avg_rpr` to get the index of these values, and then use these indices to retrieve the corresponding 'month' and 'RPR%' values.


"""

highest_rpr_month = monthly_avg_rpr.loc[monthly_avg_rpr['RPR%'].idxmax()]
lowest_rpr_month = monthly_avg_rpr.loc[monthly_avg_rpr['RPR%'].idxmin()]

print(f"Month with the highest average RPR%: {pd.to_datetime(highest_rpr_month['month']).strftime('%Y-%m-%d')} ({highest_rpr_month['RPR%']:.2f}%) ")
print(f"Month with the lowest average RPR%: {pd.to_datetime(lowest_rpr_month['month']).strftime('%Y-%m-%d')} ({lowest_rpr_month['RPR%']:.2f}%) ")

"""**Reasoning**:
To visualize the RPR% trends as requested, I will generate a line plot to show monthly RPR% by city, and two bar charts to display the average RPR% by city and by month, ensuring appropriate labels, titles, and legends for clarity.


"""

# 1. Line plot for monthly RPR% for each city
plt.figure(figsize=(15, 8))
sns.lineplot(data=rpr_df, x='month', y='RPR%', hue='city_name', marker='o')
plt.title('Monthly Repeat Passenger Rate (RPR%) by City')
plt.xlabel('Month')
plt.ylabel('Repeat Passenger Rate (%)')
plt.xticks(rotation=45)
plt.legend(title='City Name', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

# 2. Bar chart for average RPR% by city
plt.figure(figsize=(12, 7))
sns.barplot(data=city_avg_rpr.sort_values(by='RPR%', ascending=False), x='city_name', y='RPR%', palette='viridis')
plt.title('Average Repeat Passenger Rate (RPR%) by City')
plt.xlabel('City Name')
plt.ylabel('Average Repeat Passenger Rate (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. Bar chart for average RPR% by month
plt.figure(figsize=(10, 6))
sns.barplot(data=monthly_avg_rpr, x='month', y='RPR%', palette='magma')
plt.title('Average Repeat Passenger Rate (RPR%) by Month (Across All Cities)')
plt.xlabel('Month')
plt.ylabel('Average Repeat Passenger Rate (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Reasoning**:
The previous code generated `FutureWarning` messages because `palette` was used in `sns.barplot` without explicitly assigning a `hue`. To address this, I will assign the `x` variable (either `city_name` or `month`) to the `hue` parameter and set `legend=False` in both `sns.barplot` calls to ensure correct plotting and suppress the warnings, while maintaining the desired visualization.

**Reasoning**:
To assign 'Tourism' or 'Business' categories to each city in the `rpr_df` DataFrame, I will use the predefined `city_category_mapping` dictionary to create a new 'city_category' column by mapping the existing 'city_name' column. This will prepare the data for analysis of RPR% based on city type.
"""

rpr_df['city_category'] = rpr_df['city_name'].map(city_category_mapping)
rpr_df.head()

"""**Reasoning**:
To analyze the RPR% based on city type, I will group the `rpr_df` DataFrame by 'city_category' and calculate the mean of the 'RPR%' for each category. This will show the average repeat passenger rate for Tourism vs. Business cities.


"""

rpr_by_city_category = rpr_df.groupby('city_category')['RPR%'].mean().reset_index()
print("Average RPR% by city category:")
print(rpr_by_city_category)

"""**Reasoning**:
The previous code block encountered a `KeyError` which might have been due to a transient state or an issue with the DataFrame. Based on the current kernel state, the necessary columns for calculating the percentage differences are present in `master_achievement_df`. Therefore, I will re-execute the same code to categorize cities and then calculate the mean percentage differences for total trips, new passengers, and average passenger ratings, grouped by the newly added 'city_category'.

**Reasoning**:
To investigate the relationship between RPR% and average passenger ratings, I will merge `rpr_df` with `df1` on 'city_id', using a left merge to preserve all monthly RPR% data, and store the result in `rpr_with_ratings_df`.
"""

rpr_with_ratings_df = pd.merge(rpr_df, df1, on='city_id', how='left')
rpr_with_ratings_df.head()

"""**Reasoning**:
To calculate the correlation at a city level, I will first group the `rpr_with_ratings_df` by `city_name` and compute the average `RPR%` and `target_avg_passenger_rating` for each city. Then, I can calculate the correlation between these two aggregated metrics.


"""

city_level_rpr_ratings = rpr_with_ratings_df.groupby('city_name').agg(
    avg_rpr=('RPR%', 'mean'),
    avg_target_passenger_rating=('target_avg_passenger_rating', 'mean')
).reset_index()

correlation = city_level_rpr_ratings['avg_rpr'].corr(city_level_rpr_ratings['avg_target_passenger_rating'])

print(f"Correlation between Average RPR% and Average Target Passenger Rating: {correlation:.2f}")
city_level_rpr_ratings.head()

#To analyze monthly trip patterns by city category, I first added a 'city_category' column to the 'monthly_trips'DataFrame by
# mapping the 'city_name' using the predefined 'city_category_mapping'. Then, I did groupby the DataFrame by 'city_category'
#and 'month_name' to calculate the average 'total_trips' for each category, storing the result in 'monthly_trips_by_category'.

monthly_trips['city_category'] = monthly_trips['city_name'].map(city_category_mapping)
monthly_trips_by_category = monthly_trips.groupby(['city_category', 'month_name']).agg(
    average_total_trips=('total_trips', 'mean')
).reset_index()

monthly_trips_by_category.head()

"""**Reasoning**:
The previous cell produced a `FutureWarning` regarding grouping by categorical columns. To address this and explicitly acknowledge the categorical nature of 'month_name' while grouping, I will add `observed=True` to the `groupby` method. This ensures the correct behavior and suppresses the warning, maintaining the desired aggregation.


"""

monthly_trips['city_category'] = monthly_trips['city_name'].map(city_category_mapping)

monthly_trips_by_category = monthly_trips.groupby(['city_category', 'month_name'], observed=True).agg(
    average_total_trips=('total_trips', 'mean')
).reset_index()

monthly_trips_by_category.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Set the figure size for better readability
plt.figure(figsize=(12, 7))

# Create a line plot comparing monthly total trip trends between 'Tourism' and 'Business' cities
sns.lineplot(data=monthly_trips_by_category, x='month_name', y='average_total_trips', hue='city_category', marker='o')

# Add title and labels
plt.title('Monthly Average Total Trips by City Category')
plt.xlabel('Month')
plt.ylabel('Average Total Trips')

# Rotate x-axis labels if necessary
plt.xticks(rotation=45)

# Add a legend
plt.legend(title='City Category')

# Add a grid for better readability
plt.grid(True)

# Ensure tight layout
plt.tight_layout()

# Display the plot
plt.show()

"""**Reasoning**:
To explicitly state how 'Tourism' and 'Business' cities performed against their total trip targets, I will first display the relevant parts of the `categorized_achievement_summary` DataFrame.


"""

print(categorized_achievement_summary[['mean_total_trip_diff']])



"""5.	Weekend vs. Weekday Trip Demand by City
•	Compare the total trips taken on weekdays versus weekends for each city over the six-month period. Identify cities with a strong preference for

"""

trip_demand.head()

trip_demand.info()

#To easily compare trip counts between weekdays and weekends for each city, Idid unstack the trip_demand DataFrame,
#which is currently a MultiIndex Series, so that 'Weekday' and 'Weekend' become distinct columns.
trip_comparison = trip_demand.unstack(level='day_type')

trip_comparison.columns = trip_comparison.columns.droplevel(0)
trip_comparison.head()

#To quantify the preference, I am calculated the absolute difference in trip counts between weekdays and weekends,
#and then the percentage difference to understand the magnitude of the preference for each city. ABS used for positive no
trip_comparison['difference'] = abs(trip_comparison['Weekday'] - trip_comparison['Weekend'])
trip_comparison['percentage_difference'] = (trip_comparison['difference'] / trip_comparison[['Weekday', 'Weekend']].max(axis=1)) * 100

trip_comparison['preferred_day_type'] = trip_comparison.apply(lambda row: 'Weekday' if row['Weekday'] > row['Weekend'] else 'Weekend', axis=1)

trip_comparison.head()

"""**Reasoning**:
To visually represent the weekday vs. weekend trip patterns for each city, I will create a grouped bar chart using the `trip_comparison` DataFrame. This will clearly show the trip counts for each day type side-by-side for every city, allowing for easy comparison.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting by unstacking if it's not already, and resetting index
plot_data = trip_comparison[['Weekday', 'Weekend']].reset_index()
plot_data = plot_data.melt(id_vars='city_name', var_name='day_type', value_name='trip_count')

plt.figure(figsize=(15, 8))
sns.barplot(data=plot_data, x='city_name', y='trip_count', hue='day_type', palette='viridis')

plt.title('Total Trips by City and Day Type (Weekday vs. Weekend)')
plt.xlabel('City Name')
plt.ylabel('Total Trip Count')
plt.xticks(rotation=45, ha='right') # Rotate and align labels for better readability
plt.legend(title='Day Type')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()